### ISSUE TITLE
生成失败……请检查命令格式是否正确

### ISSUE THREAD

**Issue by BlackTitle** [pcrbot/5000choyen#1]
不管怎么问都是 '生成失败……请检查命令格式是否正确'
我也不懂python  所以只能提issues求助了  如果打扰了很抱歉
hoshino后台运行
`[2021-05-24 00:28:12,799 nonebot] INFO: Self: 471425760, Message 307281768 from
2775116592@[群:792730444]: '5000兆元 (上半句)|(下半句)'
[2021-05-24 00:28:12,800 5000choyen] INFO: Message 307281768 triggered gen_5000_
pic by PrefixTrigger.
[2021-05-24 00:28:12,909 nonebot] INFO: Message 307281768 is ignored`

**Comment by BlackTitle** [comment]
改了字体就好了  打扰了十分不好意思
提个建议  检测generator.py里的字体是不是初始字体，然后提醒报错

**Comment by assassingyk** [comment]
报错的判断确实没写太多……之后加个字体错误单独提醒吧）
