### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by homileak** [pcrbot/5000choyen#2]
报错信息
Traceback (most recent call last):
  File "/root/pcrbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/5000choyen/__init__.py", line 28, in gen_5000_pic
    img=genImage(word_a = upper, word_b = downer)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/5000choyen/generator.py", line 138, in genImage
    getTextWidth(word_a, font_upper, width=default_width,
  File "/root/pcrbot/HoshinoBot/hoshino/modules/5000choyen/generator.py", line 28, in getTextWidth
    if box[2] < width - step or (recursive and box[2] == width - step):
TypeError: 'NoneType' object is not subscriptable

**Comment by assassingyk** [comment]
本地测试正常，无法复现该问题，请增加有效信息，例如所用字体及所需生成的文本

**Comment by homileak** [comment]
多谢您的回复


搭建环境CentOS_7.9_64
Python版本3.9.5
bot项目地址https://github.com/Ice-Cirno/HoshinoBot/
上段字体notobk
[notobk.zip](https://github.com/pcrbot/5000choyen/files/6997849/notobk.zip)
下段字体notoserifbk
[notoserifbk.zip](https://github.com/pcrbot/5000choyen/files/6997852/notoserifbk.zip)

所生成的文本并不固定，我试了很多，文字、数字、字母、各种组合，并没有变化。

**Comment by assassingyk** [comment]
本地测试依然正常……但是这俩字体似乎简体字符缺失很多

看报错的话应该是getbbox()函数返回了None……如果要生成的句子的两个半句中某句所有字符都是缺失的话，那draw.text画出来就是空白，确实会返回None。可能你选来测试的文本碰巧都有问题……？

建议先换几个字库较完整的字体再试试。后期考虑加个特殊字符检测之类的

![L$U$XFU5B FZPY@Q1J_GAFI](https://user-images.githubusercontent.com/55473115/129685268-8ac8484b-7ccd-48e5-aa79-0ed7e934138f.png)

**Comment by homileak** [comment]
好的，我再换几个字体试试看。
多谢您的回复。

**Comment by homileak** [comment]
找到了合适的简中字体，现在正常了，非常感谢您的帮助。

这是我现在正在用的字体，效果很好，推荐您试试。
[onefont.zip](https://github.com/pcrbot/5000choyen/files/6998079/onefont.zip)
[anotherfont.zip](https://github.com/pcrbot/5000choyen/files/6998083/anotherfont.zip)

我觉得可以将这两个字体直接作为项目自带字体了。


不过有一点美中不足的就是生成的文字的下半截会被削掉一点点，不知这个能否改进一下。、
效果示例
![example](https://user-images.githubusercontent.com/48946260/129688220-d78a9736-84b8-44d9-bf70-697a441e4cdb.png)

**Comment by assassingyk** [comment]
这个可以自己按需调整相应参数，不同字体即使设置相同字号draw.text画出来的实际大小也不一样，我发布前的参数是按照我用的那俩字体调的，换别的字体肯定会有一定的偏差……

不放字体主要是版权考虑，毕竟有几个商用字体是出了名的版权流氓）

字号可以调整[这里](https://github.com/pcrbot/5000choyen/blob/b603868178d727f5c3d2dff716642326cba04af9/generator.py#L133)，字体颜色渐变范围可以调整[这几个位置](https://github.com/pcrbot/5000choyen/blob/b603868178d727f5c3d2dff716642326cba04af9/generator.py#L83)的size参数

顺便我自己用的字体调完参数大概是这个效果：
![@HX104L(TYO@NQY$UXR8E8C](https://user-images.githubusercontent.com/55473115/129693767-67712df7-8dbf-465b-ab22-4b7029af5660.PNG)

几个颜色渐变范围，尤其是黑色部分的占比会很影响视觉效果，建议根据自己的字体调整到自己觉得效果最好的程度）

（等下我把这部分加进readme里算了）

**Comment by homileak** [comment]
非常感谢，我试一试调整一下。

**Comment by homileak** [comment]
试着调整了一下，效果并是特别理想，想请问一下，可以直接用您使用的字体吗？

**Comment by assassingyk** [comment]
啊这，我只能说我用的字体名字是‘经典粗黑简’和‘方正粗宋简体’，文件我就不放了百度一下应该有……

**Comment by assassingyk** [comment]
试了下noto这个系列也还行，好像是谷歌的开源字体(?)应该没有版权问题了，顺便简化了一下参数调整的方式，等下我加进去罢

![temp](https://user-images.githubusercontent.com/55473115/129829256-da258563-23c9-4aa9-9ba2-0a76f6a445be.png)

**Comment by homileak** [comment]
非常感谢！期待您的作品。
